export enum PermissionCodes {
    leadCreate = 'lead.create',
    leadFullRead = 'lead.fullRead',
    leadRead = 'lead.read',
    leadUpdate = 'lead.update',
    leadStatus = 'lead.status',
    leadDelete = 'lead.delete',
    leadManage = 'lead.manage',
    mailSend = 'mail.send',
    companyTypeCreate = 'companyType.create',
    companyTypeRead = 'companyType.read',
    companyTypeUpdate = 'companyType.update',
    companyTypeDelete = 'companyType.delete',
    workspaceCreate = 'workspace.create',
    workspaceRead = 'workspace.read',
    workspaceUpdate = 'workspace.update',
    workspaceDelete = 'workspace.delete',
    workspaceManage = 'workspace.manage',
    usersManage = 'users.manage',
    aclRead = 'acl.read',
    aclManage = 'acl.manage',
}