version: '3.9'
services:
  backend:
    build: .
    container_name: bestcrm_backend
    networks:
      traefik:
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.crm.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.crm.entrypoints=http,https'
      - 'traefik.http.routers.crm.tls=true'
      - "traefik.http.routers.crm.tls.certresolver=letsEncrypt"

networks:
  traefik:
    external: true
