version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: bestcrm_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      default:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: bestcrm_backend
    networks:
      traefik:
      default:
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.crm.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.crm.entrypoints=http,https'
      - 'traefik.http.routers.crm.tls=true'
      - "traefik.http.routers.crm.tls.certresolver=letsEncrypt"

networks:
  traefik:
    external: true
